# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:
exec-once = hyprpaper
exec-once = mako
exec-once = [workspace 1] kitty -e btop
exec-once = [workspace 2 silent] kitty --working-directory ~/projects/lovable/lovable
exec-once = [workspace 3 silent] kitty --working-directory ~/projects/lovable/lovable1
exec-once = [workspace 4 silent] kitty --working-directory ~/projects/lovable/lovable2
exec-once = [workspace 5 silent] firefox
# exec-once = nm-applet &
