# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:
exec-once = $terminal
exec-once = hyprpaper
exec-once = [workspace 2 silent] firefox
exec-once = [workspace 1] kitty -e btop
# exec-once = nm-applet &
