
################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/

# --- EXTERNAL MONITOR SETUP ---
# monitor=eDP-1,disable
# monitor=HDMI-A-1,3840x2160@120.00Hz,auto,1.5
#
# --- BUILT-IN MONITOR SETUP ---
monitor=eDP-1,preferred,0x0,auto
monitor=HDMI-A-1,3840x2160@120.00Hz,auto,1.5

# #######################################################################################
