
workspace = 3, monitor:eDP-1, default:true
windowrule = workspace 2, match:class firefox
windowrule = workspace 3, match:class kitty
windowrule = workspace 4, match:class org.godotengine.ProjectManager
windowrule = workspace 4, match:class org.godotengine.Editor
